const donors = [
  {
    id: 1,
    name: "John Smith",
    gender: "Male",
    bloodGroup: "O+",
    email: "john.smith@email.com",
    phone: "+1 234 567 8901",
    location: "New York, USA",
    status: "Unavailable",
  },
  {
    id: 2,
    name: "Aisha Khan",
    gender: "Female",
    bloodGroup: "A+",
    email: "aisha.khan@email.com",
    phone: "+91 98765 43210",
    location: "Delhi, India",
    status: "Available",
  },
  {
    id: 3,
    name: "Rahul Verma",
    gender: "Male",
    bloodGroup: "B+",
    email: "rahul.verma@email.com",
    phone: "+91 99887 77665",
    location: "Bangalore, India",
    status: "Available",
  },
  {
    id: 4,
    name: "Emily Johnson",
    gender: "Female",
    bloodGroup: "AB-",
    email: "emily.j@email.com",
    phone: "+44 7700 900123",
    location: "London, UK",
    status: "Unavailable",
  },
  {
    id: 5,
    name: "Mohammed Ali",
    gender: "Male",
    bloodGroup: "O-",
    email: "m.ali@email.com",
    phone: "+971 55 123 4567",
    location: "Dubai, UAE",
    status: "Available",
  },
  {
    id: 6,
    name: "Sneha Patil",
    gender: "Female",
    bloodGroup: "B-",
    email: "sneha.p@email.com",
    phone: "+91 91234 56789",
    location: "Pune, India",
    status: "Available",
  },
];

export default donors;
