export const hospitals = [
  {
    id: 1,
    name: "Metro Blood Bank",
    email: "contact@metroblood.org",
    phone: "+1 555 100 2000",
    city: "Los Angeles, CA",
    license: "CA-BB-042",
    verified: true,
  },
  {
    id: 2,
    name: "LifeCare Hospital",
    email: "support@lifecare.com",
    phone: "+1 555 222 3344",
    city: "San Diego, CA",
    license: "CA-HS-118",
    verified: false,
  },
  {
    id: 3,
    name: "Red Cross Central",
    email: "info@redcrosscentral.org",
    phone: "+1 555 876 9900",
    city: "San Francisco, CA",
    license: "CA-RC-901",
    verified: true,
  },
  {
    id: 4,
    name: "Hope Medical Center",
    email: "contact@hopemed.org",
    phone: "+1 555 441 2233",
    city: "Sacramento, CA",
    license: "CA-HM-552",
    verified: false,
  },
  {
    id: 5,
    name: "Unity Blood Services",
    email: "unity@bloodservices.org",
    phone: "+1 555 909 1818",
    city: "Oakland, CA",
    license: "CA-UB-774",
    verified: true,
  },
  {
    id: 6,
    name: "City General Hospital",
    email: "admin@citygeneral.com",
    phone: "+1 555 300 4567",
    city: "San Jose, CA",
    license: "CA-CG-330",
    verified: true,
  },
];
